version: '3.7'

services:

  db:
    build: ./db
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - "db:database"
    depends_on:
      - db



